import type { Metadata } from "next";
import Link from "next/link"
import Image from "next/image"
import goldLogo from "@/images/gold-logo.svg"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-between p-10">
          <div className="flex gap-3">
            <Image src={goldLogo} alt="gold coins" width="35" height="40" />
          <h1 className="text-amber-700 text-2xl font-bold">GoldPulse</h1></div>
          <div className="links">
            <Link href="#">Home</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
