import type { Metadata } from "next";
import Link from "next/link"
import Image from "next/image"
import goldLogo from "@/images/gold-logo.svg"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        {/* Navbar */}
        <header className="bg-white shadow-md sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
            {/* Logo */}
            <div className="flex items-center gap-3">
              <Image src={goldLogo} alt="GoldPulse logo" width={35} height={40} />
              <h1 className="text-amber-700 text-2xl font-extrabold tracking-tight">
                GoldPulse
              </h1>
            </div>

            {/* Navigation links */}
            <nav className="hidden md:flex gap-6 text-gray-700 font-medium">
              <Link
                href="/"
                className="px-3 py-2 rounded-lg transition-colors duration-200 hover:bg-amber-100 hover:text-amber-700"
              >
                Home
              </Link>
              <Link
                href="/GoldCharts"
                className="px-3 py-2 rounded-lg transition-colors duration-200 hover:bg-amber-100 hover:text-amber-700"
              >
                Prices
              </Link>
              <Link
                href="/Sentiment"
                className="px-3 py-2 rounded-lg transition-colors duration-200 hover:bg-amber-100 hover:text-amber-700"
              >
                Sentiment
              </Link>
            </nav>

            {/* Optional mobile hamburger */}
            <div className="md:hidden">
              {/* Replace with your mobile menu toggle */}
              <button className="p-2 rounded-md hover:bg-gray-100 transition">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 text-gray-700"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
            </div>
          </div>
        </header>

        {/* Page content */}
        <main>{children}</main>
      </body>
    </html>
  );
}