name: Hourly Vercel Cron

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '0 * * * *'

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Function
        run: |
          curl -X GET https://gold-pulse-7tfs-2opi4bsa1-ismael-anwars-projects.vercel.app/api/Update-Sentiment